### ISSUE TITLE
0.2.1 version

### ISSUE THREAD

**Issue by sangkooki** [Bluebie/homebridge-miio#15]
on 0.2.1

I got this error message and couldn't discover my plugs. 10.0.1.28 is xiaomi gateway.

Apr 21 09:31:40 raspberrypi homebridge[25830]: [4/21/2017, 9:31:40 AM] [XiaomiMiio] device discovered 50146694
Apr 21 09:31:40 raspberrypi homebridge[25830]: [4/21/2017, 9:31:40 AM] [XiaomiMiio] Investigating Miio Device at udp://10.0.1.8:54321
Apr 21 09:31:40 raspberrypi homebridge[25830]: [4/21/2017, 9:31:40 AM] [XiaomiMiio] poll update failed on 50130438 undefined
Apr 21 09:31:41 raspberrypi homebridge[25830]: [4/21/2017, 9:31:41 AM] [XiaomiMiio] Couldn't investigate device { id: 1137364,
Apr 21 09:31:41 raspberrypi homebridge[25830]: address: '10.0.1.28',
Apr 21 09:31:41 raspberrypi homebridge[25830]: port: 54321,
Apr 21 09:31:41 raspberrypi homebridge[25830]: token: '233e5d799d1652d33d50d9f0d55843f5',
Apr 21 09:31:41 raspberrypi homebridge[25830]: lastSeen: 1492734699611,
Apr 21 09:31:41 raspberrypi homebridge[25830]: writeOnly: true } Error: Not running
Apr 21 09:31:41 raspberrypi homebridge[25830]: at Socket._healthCheck (dgram.js:525:11)
Apr 21 09:31:41 raspberrypi homebridge[25830]: at Socket.close (dgram.js:419:8)
Apr 21 09:31:41 raspberrypi homebridge[25830]: at Device.destroy (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.j
Apr 21 09:31:41 raspberrypi homebridge[25830]: at temp.call.then.then.catch.err (/usr/lib/node_modules/homebridge-miio/node_modules/mi
Apr 21 09:31:41 raspberrypi homebridge[25830]: (node:25830) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection i
Apr 21 09:31:41 raspberrypi homebridge[25830]: (node:25830) DeprecationWarning: Unhandled promise rejections are deprecated.

**Comment by Bluebie** [comment]
Unfortunately your error logs seem to be cutting off the ends of the lines, and the information provided doesn't let me track down where the issue is. It looks like an unhandled promise issue in the miio library, but it is hard to tell.

Does this happen every time you launch homebridge, or just randomly or the first time?

**Comment by sangkooki** [comment]
I'm sorry.

It's doing well now.

Thanks a lot.
