### ISSUE TITLE
Manual input

### ISSUE THREAD

**Issue by sangkooki** [Bluebie/homebridge-miio#20]
Hi,

Thanks for your efforts. It works good for me.

But I want to input 'mac address', 'name' pair manually in the config.json file.

**Comment by Bluebie** [comment]
What's the use for manual input?

**Comment by sangkooki** [comment]
Sometimes Homebridge is not working.
Then I remove the homebridge on my home app and add it again.
So I enter the name of the plug as many as I have.

**Comment by Bluebie** [comment]
do you use other platform plugins with homebridge? if it's not homebridge-miio causing the issue, it is probably a good idea to run a few copies of homebridge, so you can isolate whichever thing is causing trouble, then you wouldn't have to re-add every device each time. I regularly use several homebridges during testing and it works well.

**Comment by sangkooki** [comment]
Yes.
You are right. It's not due to your plugin.
But after re-adding, my plugs have the name of  'power plug'.
