### ISSUE TITLE
this plugin maybe conflict with others

### ISSUE THREAD

**Issue by besteric** [Bluebie/homebridge-miio#24]
my install.sh below:

```shell
cnpm install -g homebridge-aqara
cnpm install -g homebridge-yeelight
cnpm install -g homebridge-mi-air-purifier miio
cnpm install -g homebridge-miio
```

Got the error message:

```
[XiaomiMiio][39m Couldn't investigate device { id: 55235756,
  address: '192.168.1.136',
  port: 54321,
  token: '77eb5e5fa0904bf3************',
  lastSeen: 1495888130481,
  hostname: 'chuangmi-plug-m1_miio55235756',
  type: 'switch',
  model: 'chuangmi.plug.m1',
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/local/lib/node_modules/homebridge-miio/node_modules/_miio@0.7.0@miio/lib/device.js:223:23)
(node:274) UnhandledPromiseRejectionWarning: Unhandled promise rejection
```

**Comment by Bluebie** [comment]
i don't know. I only have the power socket plugs in my house. Happy to accept pull requests from anyone motivated resolve interoperability or merge support from other libraries in to this one. Conceptually there's no reason homebridge-miio couldn't support air purifiers, yeelights, aqara bridges, or any of the other wifi-based or bridged zigbee devices. the miio library even has support for many of these devices. I just don't have any of those devices to test, which makes developing support on my end a bunch of trouble.

**Comment by besteric** [comment]
@Bluebie after several times restart docker ( I run homebridge in my synology )，It can find my xiaomi power plug (V2)... Still got the error message, but it works...

**Comment by Bluebie** [comment]
Should be fixed now. Update!
