### ISSUE TITLE
Any schedule to upgrade the miio lib to the newest version?

### ISSUE THREAD

**Issue by syu-lk4b** [Bluebie/homebridge-miio#27]
Looks like the current dependencies of miio is in 0.7.0, is there any schedule to upgrade it ?anything block us to use the newest version of miio,  it has fixed a lot of bugs ,include support one of my power plugs.

**Comment by Bluebie** [comment]
The miio library's api keeps on changing. I've been putting it off until there's a 1.0 release with a stable API. Whenever that happens, i'll try and update it to the latest release and set homebridge-miio to use the most recent 1.x release available instead of locking it to a specific version.

**Comment by syu-lk4b** [comment]
Noted, thanks for the reply

**Comment by Bluebie** [comment]
updated to use miio 0.12.0
