### ISSUE TITLE
Any idea why cannot be loaded?

### ISSUE THREAD

**Issue by aguedob** [Bluebie/homebridge-miio#7]
**This is my error log:**
Mar 31 17:45:13 raspberrypi homebridge[29022]: [Fri Mar 31 2017 17:45:13 GMT+0000 (UTC)] Loaded plugin: homebridge-info
Mar 31 17:45:13 raspberrypi homebridge[29022]: [Fri Mar 31 2017 17:45:13 GMT+0000 (UTC)] Registering platform 'homebridge-info.Info'
Mar 31 17:45:13 raspberrypi homebridge[29022]: [Fri Mar 31 2017 17:45:13 GMT+0000 (UTC)] ---
Mar 31 17:45:13 raspberrypi homebridge[29022]: [Fri Mar 31 2017 17:45:13 GMT+0000 (UTC)] ====================
Mar 31 17:45:13 raspberrypi homebridge[29022]: [Fri Mar 31 2017 17:45:13 GMT+0000 (UTC)] ERROR LOADING PLUGIN homebridge-miio:
Mar 31 17:45:13 raspberrypi homebridge[29022]: [Fri Mar 31 2017 17:45:13 GMT+0000 (UTC)] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Mar 31 17:45:13 raspberrypi homebridge[29022]: at exports.runInThisContext (vm.js:53:16)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Module._compile (module.js:414:25)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Object.Module._extensions..js (module.js:442:10)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Module.load (module.js:356:32)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Function.Module._load (module.js:311:12)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Module.require (module.js:366:17)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at require (module.js:385:17)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
Mar 31 17:45:13 raspberrypi homebridge[29022]: at Array.forEach (native)

Thank you very much!

**Comment by Bluebie** [comment]
your version of node-js is too old for the javascript features homebridge-miio uses
